name: CI-Android-Develop

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android signing
        env:
          KEY_SIGN_STORE: ${{ secrets.KEY_SIGN_STORE }}
          GOOGLE_PLAY_JSON_AUTH: ${{ secrets.GOOGLE_PLAY_JSON_AUTH }}
        run: |
          # create variables
          ANDROID_KEYSTORE_PATH=$RUNNER_TEMP/android_sign_store.keystore
          GOOGLE_PLAY_AUTH_PATH=$RUNNER_TEMP/google_play_auth.json
        
          # import keystore
          echo -n "$KEY_SIGN_STORE" | base64 --decode -o $ANDROID_KEYSTORE_PATH

          # import google auth
          echo "$GOOGLE_PLAY_JSON_AUTH" > $GOOGLE_PLAY_AUTH_PATH
          
          # apply keystore
          cp $ANDROID_KEYSTORE_PATH ./auth
          cp $GOOGLE_PLAY_AUTH_PATH ./auth
          cd ./auth
          ls -a
          pwd

      - name: Build AAB with Fastlane
        run: fastlane android internal
        env:
          KEY_SIGN_PASSWORD: "${{ secrets.KEY_SIGN_PASSWORD }}"
          KEYSIGN_ALIAS: "${{ secrets.KEYSIGN_ALIAS }}"
